"""удалена модель для кэша

Revision ID: 032f9884fde3
Revises: 2c77e944fb6a
Create Date: 2025-09-19 20:46:14.857662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '032f9884fde3'
down_revision: Union[str, None] = '2c77e944fb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('azs_number', table_name='price_cache')
    op.drop_table('price_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('azs_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prices_data', mysql.JSON(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('azs_number', 'price_cache', ['azs_number'], unique=False)
    # ### end Alembic commands ###
