"""добавлена модель для кэша

Revision ID: 2c77e944fb6a
Revises: cd0bf54194d7
Create Date: 2025-09-18 19:38:35.181916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c77e944fb6a'
down_revision: Union[str, None] = 'cd0bf54194d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azs_number', sa.Integer(), nullable=True),
    sa.Column('prices_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azs_number')
    )
    op.add_column('orders', sa.Column('cheque_image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cheque_image_path')
    op.drop_table('price_cache')
    # ### end Alembic commands ###
