"""добавлено поле цена топлива

Revision ID: d144e0d945d1
Revises: d9090eb0a08d
Create Date: 2025-09-24 10:19:21.218042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd144e0d945d1'
down_revision: Union[str, None] = 'd9090eb0a08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fuel_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'fuel_price')
    # ### end Alembic commands ###
