"""модели переделаны для работы с апи банка

Revision ID: d9090eb0a08d
Revises: 032f9884fde3
Create Date: 2025-09-22 09:12:09.130358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9090eb0a08d'
down_revision: Union[str, None] = '032f9884fde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'REFUNDED', name='paymentstatus'), nullable=True))
    op.add_column('orders', sa.Column('payment_data', sa.JSON(), nullable=True))
    op.drop_column('orders', 'cheque_image_url')
    op.drop_column('orders', 'cheque_image_path')
    op.add_column('settings', sa.Column('alfa_login', sa.String(length=100), nullable=True))
    op.add_column('settings', sa.Column('alfa_password', sa.String(length=100), nullable=True))
    op.add_column('settings', sa.Column('alfa_token', sa.String(length=500), nullable=True))
    op.add_column('settings', sa.Column('alfa_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'alfa_token_expires')
    op.drop_column('settings', 'alfa_token')
    op.drop_column('settings', 'alfa_password')
    op.drop_column('settings', 'alfa_login')
    op.add_column('orders', sa.Column('cheque_image_path', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('cheque_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('orders', 'payment_data')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
